# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'thefarma' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactPushNotifications - Add these lines
  pod 'Firebase/Core', '4.2.0'
  pod 'Firebase/Messaging', '4.2.0'
  pod 'GooglePlaces'
  pod 'GoogleMaps'


  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

end
