const enums = {
	estados: ["ACRE", "ALAGOAS", "AMAZONAS", "AMAPÁ", "BAHIA", "CEARÁ", "DISTRITO FEDERAL", "ESPIRÍTO SANTO", "GOIÁS", "MARANHÃO", "MINAS GERAIS", "MATO GROSSO DO SUL", "MATO GROSO", "PARÁ", "PARAÍBA", "PERNAMBUCO", "PIAUÍ", "PARANÁ", "RIO DE JANEIRO", "RIO GRANDE DO NORTE", "RONDÔNIA", "RORAIMA", "RIO GRANDE SO SUL", "SANTA CATARINA", "SERGIPE", "SÃO PAULO", "TOCANTINS"],
	ufs: {
		"AC": "ACRE",
		"AL": "ALAGOAS",
		"AM": "AMAZONAS",
		"AP": "AMAPÁ",
		"BA": "BAHIA",
		"CE": "CEARÁ",
		"DF": "DISTRITO FEDERAL",
		"ES": "ESPIRÍTO SANTO",
		"GO": "GOIÁS",
		"MA": "MARANHÃO",
		"MG": "MINAS GERAIS",
		"MS": "MATO GROSSO DO SUL",
		"MT": "MATO GROSO",
		"PA": "PARÁ",
		"PB": "PARAÍBA",
		"PE": "PERNAMBUCO",
		"PI": "PIAUÍ",
		"PR": "PARANÁ",
		"RJ": "RIO DE JANEIRO",
		"RN": "RIO GRANDE DO NORTE",
		"RO": "RONDÔNIA",
		"RR": "RORAIMA",
		"RS": "RIO GRANDE SO SUL",
		"SC": "SANTA CATARINA",
		"SE": "SERGIPE",
		"SP": "SÃO PAULO",
		"TO": "TOCANTINS"
	}
}

export default enums;
